language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8

script:
  - xctool -workspace CrushBootstrap.xcworkspace -scheme CrushBootstrap-Staging -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_PREPROCESSOR_DEFINITIONS='${inherited} CI=1'
  # >>>bootstrap-only
  - ./bootstrap-scripts/tiramisu-expect
  - cd AmaroTest
  - xctool -workspace AmaroTest.xcworkspace -scheme AmaroTest-Staging -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' build test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_PREPROCESSOR_DEFINITIONS='${inherited} CI=1'
  # <<<bootstrap-only